### ISSUE TITLE
Update integration sample - Bynder

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-sample-app-react#143]
### Brief bug description

After the [rebranding from Kentico Cloud to Kentico Kontent](https://kontent.ai/blog/moving-to-caas-with-kentico-kontent) there are still some samples that use old naming in branches named `samples/*`.

Until the end of October endpoint on domain `kenticocloud.com` stop working and there will be redirect performed:
* https://docs.kontent.ai/reference/api-changelog#a-api-urls-changed

#### Transfer changes made in https://github.com/Kentico/kontent-sample-app-react/pull/140 to the [**`samples/bynder`**](https://github.com/Kentico/kontent-sample-app-react/tree/samples/bynder) branch

* Update dependency from `kentico-cloud-delivery` to `@kentico/kontent-delivery`
    * adjust the breaking changes
* Update dependency `@chevtek/react-spinners` to `@simply007org/react-spinners`
   * no breaking changes
* Rename Kentico Cloud to Kentico Kontent
* adjust `travis.yml` to use the correct domain for deployment

**Comment by obulaworld** [comment]
Hi @Simply007 , I can still work on this using #140

**Comment by Simply007** [comment]
Let's wait for #144 and give the opportunity to others to this one first

**Comment by obulaworld** [comment]
Hi @Simply007, can I work on this now since #144 has now been merged?

**Comment by Simply007** [comment]
@obulaworld  I have already assigned you #145 - I hope you OK with it. and assign this one to @dusekdan
