### ISSUE TITLE
Update integration sample - Google analytics

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-sample-app-react#146]
### Brief bug description

After the [rebranding from Kentico Cloud to Kentico Kontent](https://kontent.ai/blog/moving-to-caas-with-kentico-kontent) there are still some samples that use old naming in branches named `samples/*`.

Until the end of October endpoint on domain `kenticocloud.com` stop working and there will be redirect performed:
* https://docs.kontent.ai/reference/api-changelog#a-api-urls-changed

#### Transfer changes made in https://github.com/Kentico/kontent-sample-app-react/pull/140 to the [**`samples/ga`**](https://github.com/Kentico/kontent-sample-app-react/tree/samples/ga) branch

* Update dependency from `kentico-cloud-delivery` to `@kentico/kontent-delivery`
    * adjust the breaking changes
* Update dependency `@chevtek/react-spinners` to `@simply007org/react-spinners`
   * no breaking changes
* Rename Kentico Cloud to Kentico Kontent
* adjust `travis.yml` to use the correct domain for deployment

**Comment by uchemukolo** [comment]
Hello @Simply007 ,
kindly assign this task to me

**Comment by Simply007** [comment]
Hello @uchemukolo,

looking forward for the pull request!

**Comment by uchemukolo** [comment]
@Simply007 I just tried to push changes to `samples/ga branch` but i am getting the below error
`Permission Denied`
![Screenshot 2019-10-08 at 3 17 24 PM](https://user-images.githubusercontent.com/30410066/66403671-e249a700-e9de-11e9-9d91-4f5216b9321d.png)
