### ISSUE TITLE
Update integration sample - Magento

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-sample-app-react#148]
### Brief bug description

After the [rebranding from Kentico Cloud to Kentico Kontent](https://kontent.ai/blog/moving-to-caas-with-kentico-kontent) there are still some samples that use old naming in branches named `samples/*`.

Until the end of October endpoint on domain `kenticocloud.com` stop working and there will be redirect performed:
* https://docs.kontent.ai/reference/api-changelog#a-api-urls-changed

#### Transfer changes made in https://github.com/Kentico/kontent-sample-app-react/pull/140 to the [**`samples/magento`**](https://github.com/Kentico/kontent-sample-app-react/tree/samples/magento) branch

* Update dependency from `kentico-cloud-delivery` to `@kentico/kontent-delivery`
    * adjust the breaking changes
* Update dependency `@chevtek/react-spinners` to `@simply007org/react-spinners`
   * no breaking changes
* Rename Kentico Cloud to Kentico Kontent
* adjust `travis.yml` to use the correct domain for deployment

**Comment by mgroovyank** [comment]
HI! @Simply007 Can I take up this issue?

**Comment by Simply007** [comment]
@mgroovyank sure thing! 
I have assigned you the issue so that it is clear you are working on that.

**Comment by mgroovyank** [comment]
@Simply007 Thanks! I'll do it.

**Comment by Simply007** [comment]
Cool, there is a tutorial on how to set up the integration with Magento:
* https://docs.kontent.ai/tutorials/develop-apps/integrate/integrating-with-e-commerce-magento

**Comment by mgroovyank** [comment]
https://github.com/mgroovyank/kontent-sample-app-react/blob/6da3dc3b56bdae674831e3f10c13c170f69aa1af/src/App.js#L4-L6

**Comment by mgroovyank** [comment]
@Simply007 what should be the domain in travis.yml file?

**Comment by Simply007** [comment]
`https://kontent-sample-app-react-magento.surge.sh` please - please include the https at the beginning - this will enforce https event for http

**Comment by mgroovyank** [comment]
I should open the pull request to the samples/magento branch?

**Comment by Simply007** [comment]
Yes, it would be best to have a record of the fix in the pull request form.

And it is a valid contribution to [HecktoberFest](http://hacktoberfest.digitalocean.com) as well!

**Comment by Simply007** [comment]
May I ask you how did you find this issue?

I've just sent you an invitation to the Kentico GitHub organization. If you accept it, you'll be able to interact with other Kentico GitHub community members in out [Global collaborators dicsussions](https://github.com/orgs/Kentico/teams/global-collaborators) as well as getting the fresh info about Kentico Github activity.

**Comment by mgroovyank** [comment]
@Simply007 I found this issue via the hacktoberfest website.

**Comment by Simply007** [comment]
Awesome to hear that!
