### ISSUE TITLE
Update integration sample - Optimizely

### ISSUE THREAD

**Issue by Simply007** [Kentico/kontent-sample-app-react#149]
### Brief bug description

After the [rebranding from Kentico Cloud to Kentico Kontent](https://kontent.ai/blog/moving-to-caas-with-kentico-kontent) there are still some samples that use old naming in branches named `samples/*`.

Until the end of October endpoint on domain `kenticocloud.com` stop working and there will be redirect performed:
* https://docs.kontent.ai/reference/api-changelog#a-api-urls-changed

#### Transfer changes made in https://github.com/Kentico/kontent-sample-app-react/pull/140 to the [**`samples/optimizely`**](https://github.com/Kentico/kontent-sample-app-react/tree/samples/optimizely) branch

* Update dependency from `kentico-cloud-delivery` to `@kentico/kontent-delivery`
    * adjust the breaking changes
* Update dependency `@chevtek/react-spinners` to `@simply007org/react-spinners`
   * no breaking changes
* Rename Kentico Cloud to Kentico Kontent
* adjust `travis.yml` to use the correct domain for deployment

**Comment by Samuelly332** [comment]
Hi I wanna work on this Issue if I can.

**Comment by Simply007** [comment]
@Samuelly332, sure thing! 
I have assigned you the issue so that it is clear you are working on that.
