### ISSUE TITLE
Configuration admin page is not up-to-date with the latest design

### ISSUE THREAD

**Issue by PetrSvirak** [Kentico/kontent-sample-app-react#176]
### Brief bug description

The Kontent design changed quite a lot since (Admin/Configuration.js)[https://github.com/Kentico/kontent-sample-app-react/blob/master/src/Pages/Admin/Configuration.js] was last updated. It should look completely different now. Check out https://github.com/Kentico/kontent-sample-app-net/pull/128 for an inspiration.

### Repro steps

1. Clone repository fresh (or clearn up projectID)
2. Run the app
3. See the configuration in the old design:
![image](https://user-images.githubusercontent.com/15132110/120685287-fa1d4b00-c49f-11eb-9c19-dea4dae17bfc.png)

### Expected behavior

The configuration should now look like this:
![image](https://user-images.githubusercontent.com/15132110/120682352-a8bf8c80-c49c-11eb-9b2f-b2e2adc9de7a.png)

**Comment by Rezanop** [comment]
Hello,

I'm new to open source, i''d to take this one as part of my hacktoberfest participation.

**Comment by Simply007** [comment]
Hi!

This issue has gone quiet. 👻
It’s been a while since the last update here, so we are about to unassign the issue.

If we missed anything, please reply here. 

Thanks for being a part of the Kontent community!
